export const fishList = [
    {
        id: "01",  //图鉴ID
        name: "红目鲫",  //名称
        icon: require("../assets/imgFishes/f01.png"),  //icon
        shadow: "微小",  //鱼影
        //shadowIcon: require("../assets/img/fishes/mini.png"),  //鱼影图示
        sellPrice: 900,  //卖店价格
        location: "河流",  //出现地点
        appearNorth: [1, 2, 3, 11, 12],  //北半球出现月份
        appearSouth: [5, 6, 7, 8, 9],  //南半球出现月份
        northDesc: "11-3月",
        southDesc: "5-9月",
        appearTime: "全天",  //出现时间段
    },
    {
        id: "02",
        name: "溪哥",
        icon: require("../assets/imgFishes/f02.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 200,  //卖店价格
        location: "河流",
        appearNorth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        appearSouth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        northDesc: "全年",
        southDesc: "全年",
        appearTime: "9-16时",
    },
    {
        id: "03",
        name: "鲫鱼",
        icon: require("../assets/imgFishes/f03.png"),
        shadow: "小",
        shadowIcon: "",
        sellPrice: 160,  //卖店价格
        location: "河流",
        appearNorth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        appearSouth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        northDesc: "全年",
        southDesc: "全年",
        appearTime: "全天",
    },
    {
        id: "04",
        name: "雅罗鱼",
        icon: require("../assets/imgFishes/f04.png"),
        shadow: "小",
        shadowIcon: "",
        sellPrice: 240,
        location: "河流",
        appearNorth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        appearSouth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        northDesc: "全年",
        southDesc: "全年",
        appearTime: "16-9时",
    },
    {
        id: "05",
        name: "鲤鱼",
        icon: require("../assets/imgFishes/f05.png"),
        shadow: "中",
        shadowIcon: "",
        sellPrice: 300,  //卖店价格
        location: "池塘",
        appearNorth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        appearSouth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        northDesc: "全年",
        southDesc: "全年",
        appearTime: "全天",
    },
    {
        id: "06",
        name: "锦鲤",
        icon: require("../assets/imgFishes/f06.png"),
        shadow: "中",
        shadowIcon: "",
        sellPrice: 4000,  //卖店价格
        location: "池塘",
        appearNorth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        appearSouth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        northDesc: "全年",
        southDesc: "全年",
        appearTime: "16-9时",
    },
    {
        id: "07",
        name: "金鱼",
        icon: require("../assets/imgFishes/f07.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 1300,  //卖店价格
        location: "池塘",
        appearNorth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        appearSouth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        northDesc: "全年",
        southDesc: "全年",
        appearTime: "全天",
    },
    {
        id: "08",
        name: "龙睛金鱼",
        icon: require("../assets/imgFishes/f08.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 1300,  //卖店价格
        location: "池塘",
        appearNorth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        appearSouth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        northDesc: "全年",
        southDesc: "全年",
        appearTime: "9-16时",
    },
    {
        id: "09",
        name: "兰寿金鱼",
        icon: require("../assets/imgFishes/f09.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 4500,  //卖店价格
        location: "池塘",
        appearNorth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        appearSouth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        northDesc: "全年",
        southDesc: "全年",
        appearTime: "9-16时",
    },
    {
        id: "10",
        name: "稻田鱼",
        icon: require("../assets/imgFishes/f10.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 300,  //卖店价格
        location: "池塘",
        appearNorth: [4, 5, 6, 7, 8],
        appearSouth: [1, 2, 10, 11, 12],
        northDesc: "4-8月",
        southDesc: "10-2月",
        appearTime: "全天",
    },
    {
        id: "11",
        name: "淡水龙虾",
        icon: require("../assets/imgFishes/f11.png"),
        shadow: "小",
        shadowIcon: "",
        sellPrice: 200,  //卖店价格
        location: "池塘",
        appearNorth: [4, 5, 6, 7, 8, 9],
        appearSouth: [1, 2, 3, 10, 11, 12],
        northDesc: "4-9月",
        southDesc: "10-3月",
        appearTime: "全天",
    },
    {
        id: "12",
        name: "鳖",
        icon: require("../assets/imgFishes/f12.png"),
        shadow: "中",
        shadowIcon: "",
        sellPrice: 3750,  //卖店价格
        location: "河流",
        appearNorth: [8, 9],
        appearSouth: [2, 3],
        northDesc: "8-9月",
        southDesc: "2-3月",
        appearTime: "16-9时",
    },
    {
        id: "13",
        name: "拟鳄龟",
        icon: require("../assets/imgFishes/f13.png"),
        shadow: "中",
        shadowIcon: "",
        sellPrice: 5000,  //卖店价格
        location: "河流",
        appearNorth: [4, 5, 6, 7, 8, 9, 10],
        appearSouth: [1, 2, 3, 4, 10, 11, 12],
        northDesc: "4-10月",
        southDesc: "10-4月",
        appearTime: "21-4时",
    },
    {
        id: "14",
        name: "蝌蚪",
        icon: require("../assets/imgFishes/f14.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 100,  //卖店价格
        location: "池塘",
        appearNorth: [3, 4, 5, 6, 7],
        appearSouth: [1, 9, 10, 11, 12],
        northDesc: "3-7月",
        southDesc: "9-1月",
        appearTime: "全天",
    },
    {
        id: "15",
        name: "青蛙",
        icon: require("../assets/imgFishes/f15.png"),
        shadow: "小",
        shadowIcon: "",
        sellPrice: 120,  //卖店价格
        location: "池塘",
        appearNorth: [5, 6, 7, 8,],
        appearSouth: [1, 2, 11, 12],
        northDesc: "5-8月",
        southDesc: "11-2月",
        appearTime: "全天",
    },
    {
        id: "16",
        name: "塘鳢鱼",
        icon: require("../assets/imgFishes/f16.png"),
        shadow: "小",
        shadowIcon: "",
        sellPrice: 400,  //卖店价格
        location: "河流",
        appearNorth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        appearSouth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        northDesc: "全年",
        southDesc: "全年",
        appearTime: "16-9时",
    },
    {
        id: "17",
        name: "泥鳅",
        icon: require("../assets/imgFishes/f17.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 400,  //卖店价格
        location: "河流",
        appearNorth: [3, 4, 5],
        appearSouth: [9, 10, 11],
        northDesc: "3-5月",
        southDesc: "9-11月",
        appearTime: "全天",
    },
    {
        id: "18",
        name: "鲶鱼",
        icon: require("../assets/imgFishes/f18.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 200,  //卖店价格
        location: "池塘",
        appearNorth: [5, 6, 7, 8, 9, 10],
        appearSouth: [1, 2, 3, 4, 11, 12],
        northDesc: "5-10月",
        southDesc: "11-4月",
        appearTime: "16-9时",
    },
    {
        id: "19",
        name: "黑鱼",
        icon: require("../assets/imgFishes/f19.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 5500,  //卖店价格
        location: "池塘",
        appearNorth: [6, 7, 8],
        appearSouth: [1, 2, 12],
        northDesc: "6-8月",
        southDesc: "12-2月",
        appearTime: "9-16时",
    },
    {
        id: "20",
        name: "篮腮太阳鱼",
        icon: require("../assets/imgFishes/f20.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 180,  //卖店价格
        location: "河流",
        appearNorth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        appearSouth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        northDesc: "全年",
        southDesc: "全年",
        appearTime: "9-16时",
    },
    {
        id: "21",
        name: "黄鲈鱼",
        icon: require("../assets/imgFishes/f21.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 300,  //卖店价格
        location: "河流",
        appearNorth: [1, 2, 3, 10, 11, 12],
        appearSouth: [4, 5, 6, 7, 8, 9],
        northDesc: "10-3月",
        southDesc: "4-9月",
        appearTime: "全天",
    },
    {
        id: "22",
        name: "黑鲈鱼",
        icon: require("../assets/imgFishes/f22.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 400,  //卖店价格
        location: "河流",
        appearNorth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        appearSouth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        northDesc: "全年",
        southDesc: "全年",
        appearTime: "全天",
    },
    {
        id: "23",
        name: "吴郭鱼",
        icon: require("../assets/imgFishes/f23.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 800,  //卖店价格
        location: "河流",
        appearNorth: [6, 7, 8, 9, 10,],
        appearSouth: [1, 2, 3, 4, 12],
        northDesc: "6-10月",
        southDesc: "12-4月",
        appearTime: "全天",
    },
    {
        id: "24",
        name: "白斑狗鱼",
        icon: require("../assets/imgFishes/f24.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 1800,  //卖店价格
        location: "河流",
        appearNorth: [9, 10, 11, 12],
        appearSouth: [3, 4, 5, 6],
        northDesc: "9-12月",
        southDesc: "3-6月",
        appearTime: "全天",
    },
    {
        id: "25",
        name: "西太公鱼",
        icon: require("../assets/imgFishes/f25.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 400,  //卖店价格
        location: "河流",
        appearNorth: [1, 2, 12],
        appearSouth: [6, 7, 8],
        northDesc: "12-2月",
        southDesc: "6-8月",
        appearTime: "全天",
    },
    {
        id: "26",
        name: "香鱼",
        icon: require("../assets/imgFishes/f26.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 900,  //卖店价格
        location: "河流",
        appearNorth: [7, 8, 9],
        appearSouth: [1, 2, 3],
        northDesc: "7-9月",
        southDesc: "1-3月",
        appearTime: "全天",
    },
    {
        id: "27",
        name: "樱花钩吻鲑",
        icon: require("../assets/imgFishes/f27.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 1000,  //卖店价格
        location: "悬崖上",
        appearNorth: [3, 4, 5, 6, 9, 10, 11],
        appearSouth: [3, 4, 5, 9, 10, 11, 12],
        northDesc: "3-6月，9-11月",
        southDesc: "3-5月，9-12月",
        appearTime: "16-9时",
    },
    {
        id: "28",
        name: "花羔红点鲑",
        icon: require("../assets/imgFishes/f28.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 3800,  //卖店价格
        location: "悬崖上",
        appearNorth: [3, 4, 5, 6, 9, 10, 11],
        appearSouth: [3, 4, 5, 9, 10, 11, 12],
        northDesc: "3-6月，9-11月",
        southDesc: "3-5月，9-12月",
        appearTime: "16-9时",
    },
    {
        id: "29",
        name: "金鳟",
        icon: require("../assets/imgFishes/f29.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 15000,  //卖店价格
        location: "悬崖上",
        appearNorth: [3, 4, 5, 9, 10, 11],
        appearSouth: [3, 4, 5, 9, 10, 11],
        northDesc: "3-5月，9-11月",
        southDesc: "3-5月，9-11月",
        appearTime: "16-9时",
    },
    {
        id: "30",
        name: "远东哲罗鱼",
        icon: require("../assets/imgFishes/f30.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 15000,  //卖店价格
        location: "悬崖上",
        appearNorth: [1, 2, 3, 12],
        appearSouth: [6, 7, 8, 9],
        northDesc: "12-3月",
        southDesc: "6-9月",
        appearTime: "16-9时",
    },
    {
        id: "31",
        name: "鲑鱼",
        icon: require("../assets/imgFishes/f31.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 700,  //卖店价格
        location: "出海口",
        appearNorth: [9],
        appearSouth: [3],
        northDesc: "9月",
        southDesc: "3月",
        appearTime: "全天",
    },
    {
        id: "32",
        name: "帝王鲑",
        icon: require("../assets/imgFishes/f32.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 1800,  //卖店价格
        location: "出海口",
        appearNorth: [9],
        appearSouth: [3],
        northDesc: "9月",
        southDesc: "3月",
        appearTime: "全天",
    },
    {
        id: "33",
        name: "中华绒螯蟹",
        icon: require("../assets/imgFishes/f33.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 2000,  //卖店价格
        location: "河流",
        appearNorth: [9, 10, 11],
        appearSouth: [3, 4, 5],
        northDesc: "9-11月",
        southDesc: "3-5月",
        appearTime: "16-9时",
    },
    {
        id: "34",
        name: "孔雀鱼",
        icon: require("../assets/imgFishes/f34.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 1300,  //卖店价格
        location: "河流",
        appearNorth: [4, 5, 6, 7, 8, 9, 10, 11],
        appearSouth: [1, 2, 3, 4, 5, 10, 11, 12],
        northDesc: "4-11月",
        southDesc: "10-5月",
        appearTime: "9-16时",
    },
    {
        id: "35",
        name: "温泉医生鱼",
        icon: require("../assets/imgFishes/f35.png"),
        shadow: "",
        shadowIcon: "",
        sellPrice: 1500,  //卖店价格
        location: "河流",
        appearNorth: [5, 6, 7, 8, 9],
        appearSouth: [1, 2, 3, 11, 12],
        northDesc: "5-9月",
        southDesc: "11-3月",
        appearTime: "9-16时",
    },
    {
        id: "36",
        name: "神仙鱼",
        icon: require("../assets/imgFishes/f36.png"),
        shadow: "",
        shadowIcon: "",
        sellPrice: 3000,  //卖店价格
        location: "河流",
        appearNorth: [5, 6, 7, 8, 9, 10],
        appearSouth: [1, 2, 3, 4, 11, 12],
        northDesc: "5-10月",
        southDesc: "11-4月",
        appearTime: "16-9时",
    },
    {
        id: "37",
        name: "斗鱼",
        icon: require("../assets/imgFishes/f37.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 2500,  //卖店价格
        location: "河流",
        appearNorth: [5, 6, 7, 8, 9, 10],
        appearSouth: [1, 2, 3, 4, 11, 12],
        northDesc: "5-10月",
        southDesc: "11-4月",
        appearTime: "9-16时",
    },
    {
        id: "38",
        name: "霓虹灯鱼",
        icon: require("../assets/imgFishes/f38.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 500,  //卖店价格
        location: "河流",
        appearNorth: [4, 5, 6, 7, 8, 9, 10, 11],
        appearSouth: [1, 2, 3, 4, 5, 10, 11, 12],
        northDesc: "4-11月",
        southDesc: "10-5月",
        appearTime: "9-16时",
    },
    {
        id: "39",
        name: "彩虹鱼",
        icon: require("../assets/imgFishes/f39.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 800,  //卖店价格
        location: "河流",
        appearNorth: [5, 6, 7, 8, 9, 10],
        appearSouth: [1, 2, 3, 4, 11, 12],
        northDesc: "5-10月",
        southDesc: "11-4月",
        appearTime: "9-16时",
    },
    {
        id: "40",
        name: "食人鱼",
        icon: require("../assets/imgFishes/f40.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 2500,  //卖店价格
        location: "河流",
        appearNorth: [6, 7, 8, 9],
        appearSouth: [1, 2, 3, 12],
        northDesc: "6-9月",
        southDesc: "12-3月",
        appearTime: "9-16时，21-4时",
    },
    {
        id: "41",
        name: "骨舌鱼",
        icon: require("../assets/imgFishes/f41.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 10000,  //卖店价格
        location: "河流",
        appearNorth: [6, 7, 8, 9],
        appearSouth: [1, 2, 3, 12],
        northDesc: "6-9月",
        southDesc: "12-3月",
        appearTime: "16-9时",
    },
    {
        id: "42",
        name: "黄金河虎",
        icon: require("../assets/imgFishes/f42.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 15000,  //卖店价格
        location: "河流",
        appearNorth: [6, 7, 8, 9],
        appearSouth: [1, 2, 3, 12],
        northDesc: "6-9月",
        southDesc: "12-3月",
        appearTime: "4-24时",
    },
    {
        id: "43",
        name: "雀鳝",
        icon: require("../assets/imgFishes/f43.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 6000,  //卖店价格
        location: "池塘",
        appearNorth: [6, 7, 8, 9],
        appearSouth: [1, 2, 3, 12],
        northDesc: "6-9月",
        southDesc: "12-3月",
        appearTime: "16-9时",
    },
    {
        id: "44",
        name: "巨骨舌鱼",
        icon: require("../assets/imgFishes/f44.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 10000,  //卖店价格
        location: "河流",
        appearNorth: [6, 7, 8, 9],
        appearSouth: [1, 2, 3, 12],
        northDesc: "6-9月",
        southDesc: "12-3月",
        appearTime: "16-9时",
    },
    {
        id: "45",
        name: "恩氏多鳍鱼",
        icon: require("../assets/imgFishes/f45.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 4000,  //卖店价格
        location: "河流",
        appearNorth: [6, 7, 8, 9],
        appearSouth: [1, 2, 3, 12],
        northDesc: "6-9月",
        southDesc: "12-3月",
        appearTime: "21-4时",
    },
    {
        id: "46",
        name: "鲟鱼",
        icon: require("../assets/imgFishes/f46.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 10000,  //卖店价格
        location: "出海口",
        appearNorth: [1, 2, 3, 9, 10, 11, 12],
        appearSouth: [3, 4, 5, 6, 7, 8, 9],
        northDesc: "9-3月",
        southDesc: "3-9月",
        appearTime: "全天",
    },
    {
        id: "47",
        name: "海蝴蝶",
        icon: require("../assets/imgFishes/f47.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 1000,  //卖店价格
        location: "大海",
        appearNorth: [1, 2, 3, 12],
        appearSouth: [6, 7, 8, 9],
        northDesc: "12-3月",
        southDesc: "6-9月",
        appearTime: "全天",
    },
    {
        id: "48",
        name: "海马",
        icon: require("../assets/imgFishes/f48.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 1100,  //卖店价格
        location: "大海",
        appearNorth: [4, 5, 6, 7, 8, 9, 10, 11],
        appearSouth: [1, 2, 3, 4, 5, 10, 11, 12],
        northDesc: "4-11月",
        southDesc: "10-5月",
        appearTime: "全天",
    },
    {
        id: "49",
        name: "小丑鱼",
        icon: require("../assets/imgFishes/f49.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 650,  //卖店价格
        location: "大海",
        appearNorth: [4, 5, 6, 7, 8, 9],
        appearSouth: [1, 2, 3, 10, 11, 12],
        northDesc: "4-9月",
        southDesc: "10-3月",
        appearTime: "全天",
    },
    {
        id: "50",
        name: "拟刺尾鲷",
        icon: require("../assets/imgFishes/f50.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 1000,  //卖店价格
        location: "大海",
        appearNorth: [4, 5, 6, 7, 8, 9],
        appearSouth: [1, 2, 3, 10, 11, 12],
        northDesc: "4-9月",
        southDesc: "10-3月",
        appearTime: "全天",
    },
    {
        id: "51",
        name: "耳带蝴蝶鱼",
        icon: require("../assets/imgFishes/f51.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 1000,  //卖店价格
        location: "大海",
        appearNorth: [4, 5, 6, 7, 8, 9],
        appearSouth: [1, 2, 3, 10, 11, 12],
        northDesc: "4-9月",
        southDesc: "10-3月",
        appearTime: "全天",
    },
    {
        id: "52",
        name: "苏眉鱼",
        icon: require("../assets/imgFishes/f52.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 10000,  //卖店价格
        location: "大海",
        appearNorth: [7, 8],
        appearSouth: [1, 2],
        northDesc: "7-8月",
        southDesc: "1-2月",
        appearTime: "0-21时",
    },
    {
        id: "53",
        name: "狮子鱼",
        icon: require("../assets/imgFishes/f53.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 500,  //卖店价格
        location: "大海",
        appearNorth: [4, 5, 6, 7, 8, 9, 10, 11],
        appearSouth: [1, 2, 3, 4, 5, 10, 11, 12],
        northDesc: "4-11月",
        southDesc: "10-5月",
        appearTime: "全天",
    },
    {
        id: "54",
        name: "河豚",
        icon: require("../assets/imgFishes/f54.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 5000,  //卖店价格
        location: "大海",
        appearNorth: [1, 2, 11, 12],
        appearSouth: [5, 6, 7, 8],
        northDesc: "11-2月",
        southDesc: "5-8月",
        appearTime: "21-4时",
    },
    {
        id: "55",
        name: "刺豚",
        icon: require("../assets/imgFishes/f55.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 250,  //卖店价格
        location: "大海",
        appearNorth: [7, 8, 9],
        appearSouth: [1, 2, 3],
        northDesc: "7-9月",
        southDesc: "1-3月",
        appearTime: "全天",
    },
    {
        id: "56",
        name: "凤尾鱼",
        icon: require("../assets/imgFishes/f56.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 200,  //卖店价格
        location: "大海",
        appearNorth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        appearSouth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        northDesc: "全年",
        southDesc: "全年",
        appearTime: "4-21时",
    },
    {
        id: "57",
        name: "竹荚鱼",
        icon: require("../assets/imgFishes/f57.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 150,  //卖店价格
        location: "大海",
        appearNorth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        appearSouth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        northDesc: "全年",
        southDesc: "全年",
        appearTime: "全天",
    },
    {
        id: "58",
        name: "条石鲷",
        icon: require("../assets/imgFishes/f58.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 5000,  //卖店价格
        location: "大海",
        appearNorth: [3, 4, 5, 6, 7, 8, 9, 10, 11],
        appearSouth: [1, 2, 3, 4, 5, 9, 10, 11, 12],
        northDesc: "3-11月",
        southDesc: "9-5月",
        appearTime: "全天",
    },
    {
        id: "59",
        name: "鲈鱼",
        icon: require("../assets/imgFishes/f59.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 400,  //卖店价格
        location: "大海",
        appearNorth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        appearSouth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        northDesc: "全年",
        southDesc: "全年",
        appearTime: "全天",
    },
    {
        id: "60",
        name: "鲷鱼",
        icon: require("../assets/imgFishes/f60.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 3000,  //卖店价格
        location: "大海",
        appearNorth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        appearSouth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        northDesc: "全年",
        southDesc: "全年",
        appearTime: "全天",
    },
    {
        id: "61",
        name: "鲽鱼",
        icon: require("../assets/imgFishes/f61.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 300,  //卖店价格
        location: "大海",
        appearNorth: [1, 2, 3, 4, 10, 11, 12],
        appearSouth: [4, 5, 6, 7, 8, 9, 10],
        northDesc: "10-4月",
        southDesc: "4-10月",
        appearTime: "全天",
    },
    {
        id: "62",
        name: "比目鱼",
        icon: require("../assets/imgFishes/f62.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 800,  //卖店价格
        location: "大海",
        appearNorth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        appearSouth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        northDesc: "全年",
        southDesc: "全年",
        appearTime: "全天",
    },
    {
        id: "63",
        name: "鱿鱼",
        icon: require("../assets/imgFishes/f63.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 500,  //卖店价格
        location: "大海",
        appearNorth: [1, 2, 3, 4, 5, 6, 7, 8, 12],
        appearSouth: [1, 2, 6, 7, 8, 9, 10, 11, 12],
        northDesc: "12-8月",
        southDesc: "6-2月",
        appearTime: "全天",
    },
    {
        id: "64",
        name: "裸胸鳝",
        icon: require("../assets/imgFishes/f64.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 2000,  //卖店价格
        location: "大海",
        appearNorth: [8, 9, 10],
        appearSouth: [2, 3, 4],
        northDesc: "8-10月",
        southDesc: "2-4月",
        appearTime: "全天",
    },
    {
        id: "65",
        name: "五彩鳗",
        icon: require("../assets/imgFishes/f65.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 600,  //卖店价格
        location: "大海",
        appearNorth: [6, 7, 8, 9, 10],
        appearSouth: [1, 2, 3, 4, 12],
        northDesc: "6-10月",
        southDesc: "12-4月",
        appearTime: "全天",
    },
    {
        id: "66",
        name: "鲔鱼",
        icon: require("../assets/imgFishes/f66.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 7000,  //卖店价格
        location: "码头",
        appearNorth: [1, 2, 3, 4, 11, 12],
        appearSouth: [5, 6, 7, 8, 9],
        northDesc: "11-4月",
        southDesc: "5-9月",
        appearTime: "全天",
    },
    {
        id: "67",
        name: "旗鱼",
        icon: require("../assets/imgFishes/f67.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 10000,  //卖店价格
        location: "码头",
        appearNorth: [1, 2, 3, 4, 7, 8, 9, 11, 12],
        appearSouth: [1, 2, 3, 5, 6, 7, 8, 9, 10],
        northDesc: "7-9月，11-4月",
        southDesc: "1-3月，5-10月",
        appearTime: "全天",
    },
    {
        id: "68",
        name: "白面弄鱼",
        icon: require("../assets/imgFishes/f68.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 4500,  //卖店价格
        location: "码头",
        appearNorth: [5, 6, 7, 8, 9, 10],
        appearSouth: [1, 2, 3, 4, 11, 12],
        northDesc: "5-10月",
        southDesc: "11-4月",
        appearTime: "全天",
    },
    {
        id: "69",
        name: "鬼头刀",
        icon: require("../assets/imgFishes/f69.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 12000,  //卖店价格
        location: "码头",
        appearNorth: [5, 6, 7, 8, 9, 10],
        appearSouth: [1, 2, 3, 4, 11, 12],
        northDesc: "5-10月",
        southDesc: "11-4月",
        appearTime: "全天",
    },
    {
        id: "70",
        name: "翻车鱼",
        icon: require("../assets/imgFishes/f70.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 4000,  //卖店价格
        location: "大海",
        appearNorth: [7, 8, 9],
        appearSouth: [1, 2, 3],
        northDesc: "7-9月",
        southDesc: "1-3月",
        appearTime: "4-21时",
    },
    {
        id: "71",
        name: "鹞鱼",
        icon: require("../assets/imgFishes/f71.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 3000,  //卖店价格
        location: "大海",
        appearNorth: [8, 9],
        appearSouth: [2, 3, 4, 5],
        northDesc: "8-9月",
        southDesc: "2-5月",
        appearTime: "4-21时",
    },
    {
        id: "72",
        name: "锯鲨",
        icon: require("../assets/imgFishes/f72.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 12000,  //卖店价格
        location: "大海",
        appearNorth: [6, 7, 8, 9],
        appearSouth: [1, 2, 3, 12],
        northDesc: "6-9月",
        southDesc: "12-3月",
        appearTime: "16-9时",
    },
    {
        id: "73",
        name: "双髻鲨",
        icon: require("../assets/imgFishes/f73.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 8000,  //卖店价格
        location: "大海",
        appearNorth: [6, 7, 8, 9],
        appearSouth: [1, 2, 3, 12],
        northDesc: "6-9月",
        southDesc: "12-3月",
        appearTime: "16-9时",
    },
    {
        id: "74",
        name: "鲨鱼",
        icon: require("../assets/imgFishes/f74.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 15000,  //卖店价格
        location: "大海",
        appearNorth: [6, 7, 8, 9],
        appearSouth: [1, 2, 3, 12],
        northDesc: "6-9月",
        southDesc: "12-3月",
        appearTime: "16-9时",
    },
    {
        id: "75",
        name: "鲸鲨",
        icon: require("../assets/imgFishes/f75.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 13000,  //卖店价格
        location: "大海",
        appearNorth: [6, 7, 8, 9],
        appearSouth: [1, 2, 3, 12],
        northDesc: "6-9月",
        southDesc: "12-3月",
        appearTime: "全天",
    },
    {
        id: "76",
        name: "吸盘鱼",
        icon: require("../assets/imgFishes/f76.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 1500,  //卖店价格
        location: "大海",
        appearNorth: [6, 7, 8, 9],
        appearSouth: [1, 2, 3, 12],
        northDesc: "6-9月",
        southDesc: "12-3月",
        appearTime: "全天",
    },
    {
        id: "77",
        name: "灯笼鱼",
        icon: require("../assets/imgFishes/f77.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 2500,  //卖店价格
        location: "大海",
        appearNorth: [1, 2, 3, 11, 12],
        appearSouth: [5, 6, 7, 8, 9],
        northDesc: "11-3月",
        southDesc: "5-9月",
        appearTime: "16-9时",
    },
    {
        id: "78",
        name: "皇带鱼",
        icon: require("../assets/imgFishes/f78.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 9000,  //卖店价格
        location: "大海",
        appearNorth: [1, 2, 3, 4, 5, 12],
        appearSouth: [6, 7, 8, 9, 10, 11],
        northDesc: "12-5月",
        southDesc: "6-11月",
        appearTime: "全天",
    },
    {
        id: "79",
        name: "太平洋桶眼鱼",
        icon: require("../assets/imgFishes/f79.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 15000,  //卖店价格
        location: "大海",
        appearNorth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        appearSouth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        northDesc: "全年",
        southDesc: "全年",
        appearTime: "21-4时",
    },
    {
        id: "80",
        name: "矛尾鱼",
        icon: require("../assets/imgFishes/f80.png"),
        shadow: "微小",
        shadowIcon: "",
        sellPrice: 15000,  //卖店价格
        location: "大海",
        appearNorth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        appearSouth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        northDesc: "全年",
        southDesc: "全年",
        appearTime: "下雨天",
    }
]