export const insectList = [
    {
        id: "01",  //图鉴ID
        name: "白粉蝶",  //名称
        //icon: require("../assets/img/fishes/01.png"),  //icon
        shadow: "",  //鱼影
        //shadowIcon: require("../assets/img/fishes/mini.png"),  //鱼影图示
        sellPrice: 160,  //卖店价格
        location: "",  //出现地点
        appearNorth: [1, 2, 3, 4, 5, 6, 9, 10, 11, 12],  //北半球出现月份
        appearSouth: [3, 4, 5, 6, 7, 8, 9, 10, 11, 12],  //南半球出现月份
        northDesc: "9-6月",
        southDesc: "3-12月",
        appearTime: "4-19时",  //出现时间段
    },
    {
        id: "02",
        name: "斑缘点粉蝶",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 160,  //卖店价格
        location: "",
        appearNorth: [3, 4, 5, 6, 9, 10],
        appearSouth: [3, 4, 9, 10, 11, 12],
        northDesc: "3-6月，9-10月",
        southDesc: "3-4月，9-12月",
        appearTime: "4-19时",
    },
    {
        id: "03",
        name: "凤蝶",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 240,  //卖店价格
        location: "",
        appearNorth: [3, 4, 5, 6, 7, 8, 9],
        appearSouth: [1, 2, 3, 9, 10, 11, 12],
        northDesc: "3-9月",
        southDesc: "9-3月",
        appearTime: "4-19时",
    },
    {
        id: "04",
        name: "乌鸦凤蝶",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 2500,
        location: "",
        appearNorth: [3, 4, 5, 6],
        appearSouth: [9, 10, 11, 12],
        northDesc: "3-6月",
        southDesc: "9-12月",
        appearTime: "0-19时",
    },
    {
        id: "05",
        name: "清带凤蝶",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 300,  //卖店价格
        location: "",
        appearNorth: [4, 5, 6, 7, 8],
        appearSouth: [1, 2, 10, 11, 12],
        northDesc: "4-8月",
        southDesc: "10-2月",
        appearTime: "4-20时",
    },
    {
        id: "06",
        name: "大白斑蝶",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 1000,  //卖店价格
        location: "",
        appearNorth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        appearSouth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        northDesc: "全年",
        southDesc: "全年",
        appearTime: "8-19时",
    },
    {
        id: "07",
        name: "大紫蛱蝶",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 3000,  //卖店价格
        location: "",
        appearNorth: [5, 6, 7, 8],
        appearSouth: [1, 2, 11, 12],
        northDesc: "5-8月",
        southDesc: "11-2月",
        appearTime: "4-19时",
    },
    {
        id: "08",
        name: "大桦斑蝶",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 140,  //卖店价格
        location: "",
        appearNorth: [9, 10, 11],
        appearSouth: [3, 4, 5],
        northDesc: "9-11月",
        southDesc: "3-5月",
        appearTime: "4-17时",
    },
    {
        id: "09",
        name: "大蓝闪蝶",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 4000,  //卖店价格
        location: "",
        appearNorth: [1, 2, 3, 6, 7, 8, 9, 12],
        appearSouth: [1, 2, 3, 6, 7, 8, 9, 12],
        northDesc: "6-9月，12-3月",
        southDesc: "6-9月，12-3月",
        appearTime: "17-8时",
    },
    {
        id: "10",
        name: "彩袄蛱蝶",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 3000,  //卖店价格
        location: "",
        appearNorth: [4, 5, 6, 7, 8, 9],
        appearSouth: [1, 2, 3, 10, 11, 12],
        northDesc: "4-9月",
        southDesc: "10-3月",
        appearTime: "8-17时",
    },
    {
        id: "11",
        name: "红颈凤蝶",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 2500,  //卖店价格
        location: "",
        appearNorth: [1, 2, 4, 5, 6, 7, 8, 9, 12],
        appearSouth: [1, 2, 3, 6, 7, 8, 10, 11, 12],
        northDesc: "4-9月，12-2月",
        southDesc: "6-8月，10-3月",
        appearTime: "8-17时",
    },
    {
        id: "12",
        name: "亚历山大蝶",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 4000,  //卖店价格
        location: "",
        appearNorth: [5, 6, 7, 8, 9],
        appearSouth: [1, 2, 3, 11, 12],
        northDesc: "5-9月",
        southDesc: "11-3月",
        appearTime: "8-16时",
    },
    {
        id: "13",
        name: "飞蛾",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 130,  //卖店价格
        location: "夜晚灯光附近",
        appearNorth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        appearSouth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        northDesc: "全年",
        southDesc: "全年",
        appearTime: "19-4时",
    },
    {
        id: "14",
        name: "皇蛾",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 3000,  //卖店价格
        location: "",
        appearNorth: [4, 5, 6, 7, 8, 9],
        appearSouth: [1, 2, 3, 10, 11, 12],
        northDesc: "4-9月",
        southDesc: "10-3月",
        appearTime: "19-4时",
    },
    {
        id: "15",
        name: "日落蛾",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 2500,  //卖店价格
        location: "",
        appearNorth: [4, 5, 6, 7, 8, 9],
        appearSouth: [1, 2, 3, 10, 11, 12],
        northDesc: "4-9月",
        southDesc: "10-3月",
        appearTime: "8-16时",
    },
    {
        id: "16",
        name: "中华剑角蝗",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 200,  //卖店价格
        location: "",
        appearNorth: [4, 5, 6, 7, 8, 9, 10, 11],
        appearSouth: [1, 2, 3, 4, 5, 10, 11, 12],
        northDesc: "4-11月",
        southDesc: "10-5月",
        appearTime: "8-19时",
    },
    {
        id: "17",
        name: "飞蝗",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 600,  //卖店价格
        location: "",
        appearNorth: [8, 9, 10, 11],
        appearSouth: [2, 3, 4, 5],
        northDesc: "8-11月",
        southDesc: "2-5月",
        appearTime: "8-19时",
    },
    {
        id: "18",
        name: "稻蝗",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 400,  //卖店价格
        location: "",
        appearNorth: [8, 9, 10, 11],
        appearSouth: [2, 3, 4, 5],
        northDesc: "8-11月",
        southDesc: "2-5月",
        appearTime: "8-19时",
    },
    {
        id: "19",
        name: "蚱蜢",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 160,  //卖店价格
        location: "",
        appearNorth: [7, 8, 9],
        appearSouth: [1, 2, 3],
        northDesc: "7-9月",
        southDesc: "1-3月",
        appearTime: "8-17时",
    },
    {
        id: "20",
        name: "蟋蟀",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 130,  //卖店价格
        location: "",
        appearNorth: [9, 10, 11],
        appearSouth: [3, 4, 5],
        northDesc: "9-11月",
        southDesc: "3-5月",
        appearTime: "17-8时",
    },
    {
        id: "21",
        name: "铃虫",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 430,  //卖店价格
        location: "",
        appearNorth: [9, 10],
        appearSouth: [3, 4],
        northDesc: "9-10月",
        southDesc: "3-4月",
        appearTime: "17-8时",
    },
    {
        id: "22",
        name: "螳螂",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 430,  //卖店价格
        location: "花朵附近",
        appearNorth: [3, 4, 5, 6, 7, 8, 9, 10, 11],
        appearSouth: [1, 2, 3, 4, 5, 9, 10, 11, 12],
        northDesc: "3-11月",
        southDesc: "9-5月",
        appearTime: "8-17时",
    },
    {
        id: "23",
        name: "兰花螳螂",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 2400,  //卖店价格
        location: "花朵附近",
        appearNorth: [3, 4, 5, 6, 7, 8, 9, 10, 11],
        appearSouth: [1, 2, 3, 4, 5, 9, 10, 11, 12],
        northDesc: "3-11月",
        southDesc: "9-5月",
        appearTime: "8-17时",
    },
    {
        id: "24",
        name: "蜜蜂",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 200,  //卖店价格
        location: "花朵附近",
        appearNorth: [3, 4, 5, 6, 7],
        appearSouth: [1, 9, 10, 11, 12],
        northDesc: "3-7月",
        southDesc: "9-1月",
        appearTime: "8-17时",
    },
    {
        id: "25",
        name: "黄蜂",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 2500,  //卖店价格
        location: "蜂巢",
        appearNorth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        appearSouth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        northDesc: "全年",
        southDesc: "全年",
        appearTime: "全天",
    },
    {
        id: "26",
        name: "油蝉",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 250,  //卖店价格
        location: "树干",
        appearNorth: [7, 8],
        appearSouth: [1, 2],
        northDesc: "7-8月",
        southDesc: "1-2月",
        appearTime: "8-17时",
    },
    {
        id: "27",
        name: "斑透翅蝉",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 300,  //卖店价格
        location: "树干",
        appearNorth: [7, 8],
        appearSouth: [1, 2],
        northDesc: "7-8月",
        southDesc: "1-2月",
        appearTime: "8-17时",
    },
    {
        id: "28",
        name: "熊蝉",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 500,  //卖店价格
        location: "树干",
        appearNorth: [7, 8],
        appearSouth: [1, 2],
        northDesc: "7-8月",
        southDesc: "1-2月",
        appearTime: "8-17时",
    },
    {
        id: "29",
        name: "寒蝉",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 400,  //卖店价格
        location: "树干",
        appearNorth: [8, 9],
        appearSouth: [2, 3],
        northDesc: "8-9月",
        southDesc: "2-3月",
        appearTime: "8-17时",
    },
    {
        id: "30",
        name: "暮蝉",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 550,  //卖店价格
        location: "树干",
        appearNorth: [7, 8],
        appearSouth: [1, 2],
        northDesc: "7-8月",
        southDesc: "1-2月",
        appearTime: "??-8时，16-19时",
    },
    {
        id: "31",
        name: "蝉蜕",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 10,  //卖店价格
        location: "树干",
        appearNorth: [7, 8],
        appearSouth: [1, 2],
        northDesc: "7-8月",
        southDesc: "1-2月",
        appearTime: "全天",
    },
    {
        id: "32",
        name: "红蜻蜓",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 180,  //卖店价格
        location: "水边",
        appearNorth: [9, 10],
        appearSouth: [3, 4],
        northDesc: "9-10月",
        southDesc: "3-4月",
        appearTime: "8-19时",
    },
    {
        id: "33",
        name: "绿胸晏蜓",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 230,  //卖店价格
        location: "水边",
        appearNorth: [4, 5, 6, 7, 8, 9, 10],
        appearSouth: [1, 2, 3, 4, 10, 11, 12],
        northDesc: "4-10月",
        southDesc: "10-4月",
        appearTime: "8-17时",
    },
    {
        id: "34",
        name: "无霸勾蜓",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 4500,  //卖店价格
        location: "水边",
        appearNorth: [5, 6, 7, 8, 9, 10],
        appearSouth: [1, 2, 3, 4, 11, 12],
        northDesc: "5-10月",
        southDesc: "11-4月",
        appearTime: "8-17时",
    },
    {
        id: "35",
        name: "豆娘",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 500,  //卖店价格
        location: "水边",
        appearNorth: [1, 2, 11, 12],
        appearSouth: [5, 6, 7, 8],
        northDesc: "11-2月",
        southDesc: "5-8月",
        appearTime: "全天",
    },
    {
        id: "36",
        name: "萤火虫",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 300,  //卖店价格
        location: "淡水附近",
        appearNorth: [6],
        appearSouth: [12],
        northDesc: "6月",
        southDesc: "12月",
        appearTime: "19-4时",
    },
    {
        id: "37",
        name: "蝼蛄",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 500,  //卖店价格
        location: "地下，听声音挖地",
        appearNorth: [1, 2, 3, 4, 5, 11, 12],
        appearSouth: [5, 6, 7, 8, 9, 10, 11],
        northDesc: "11-5月",
        southDesc: "5-11月",
        appearTime: "全天",
    },
    {
        id: "38",
        name: "水黾",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 130,  //卖店价格
        location: "水面",
        appearNorth: [5, 6, 7, 8, 9],
        appearSouth: [1, 2, 3, 11, 12],
        northDesc: "5-9月",
        southDesc: "11-3月",
        appearTime: "8-19时",
    },
    {
        id: "39",
        name: "龙虱",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 800,  //卖店价格
        location: "水面",
        appearNorth: [5, 6, 7, 8, 9],
        appearSouth: [1, 2, 3, 11, 12],
        northDesc: "5-9月",
        southDesc: "11-3月",
        appearTime: "19-8时",
    },
    {
        id: "40",
        name: "田鳖",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 2000,  //卖店价格
        location: "水面",
        appearNorth: [4, 5, 6, 7, 8, 9],
        appearSouth: [1, 2, 3, 10, 11, 12],
        northDesc: "4-9月",
        southDesc: "10-3月",
        appearTime: "19-8时",
    },
    {
        id: "41",
        name: "椿象",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 120,  //卖店价格
        location: "花朵上",
        appearNorth: [3, 4, 5, 6, 7, 8, 9, 10],
        appearSouth: [1, 2, 3, 4, 9, 10, 11, 12],
        northDesc: "3-10月",
        southDesc: "9-4月",
        appearTime: "全天",
    },
    {
        id: "42",
        name: "人面椿象",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 1000,  //卖店价格
        location: "花朵上",
        appearNorth: [3, 4, 5, 6, 7, 8, 9, 10],
        appearSouth: [1, 2, 3, 4, 9, 10, 11, 12],
        northDesc: "3-10月",
        southDesc: "9-4月",
        appearTime: "19-8时",
    },
    {
        id: "43",
        name: "瓢虫",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 200,  //卖店价格
        location: "花朵上",
        appearNorth: [3, 4, 5, 6, 10],
        appearSouth: [4, 9, 10, 11, 12],
        northDesc: "3-6月，10月",
        southDesc: "4月，9-12月",
        appearTime: "8-17时",
    },
    {
        id: "44",
        name: "虎甲虫",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 1500,  //卖店价格
        location: "",
        appearNorth: [2, 3, 4, 5, 6, 7, 8, 9, 10],
        appearSouth: [1, 2, 3, 4, 8, 9, 10, 11, 12],
        northDesc: "2-10月",
        southDesc: "8-4月",
        appearTime: "全天",
    },
    {
        id: "45",
        name: "吉丁虫",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 2400,  //卖店价格
        location: "树桩",
        appearNorth: [4, 5, 6, 7, 8],
        appearSouth: [1, 2, 10, 11, 12],
        northDesc: "4-8月",
        southDesc: "10-2月",
        appearTime: "全天",
    },
    {
        id: "46",
        name: "提琴虫",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 450,  //卖店价格
        location: "树桩",
        appearNorth: [5, 6, 9, 10, 11],
        appearSouth: [3, 4, 5, 11, 12],
        northDesc: "5-6月，9-11月",
        southDesc: "3-5月，11-12月",
        appearTime: "全天",
    },
    {
        id: "47",
        name: "星天牛",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 350,  //卖店价格
        location: "树桩",
        appearNorth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        appearSouth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        northDesc: "全年",
        southDesc: "全年",
        appearTime: "全天",
    },
    {
        id: "48",
        name: "琉璃星天牛",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 3000,  //卖店价格
        location: "树桩",
        appearNorth: [5, 6, 7, 8, 9],
        appearSouth: [1, 2, 3, 11, 12],
        northDesc: "5-9月",
        southDesc: "11-3月",
        appearTime: "全天",
    },
    {
        id: "49",
        name: "宝石象鼻虫",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 800,  //卖店价格
        location: "树干",
        appearNorth: [7, 8],
        appearSouth: [1, 2],
        northDesc: "7-8月",
        southDesc: "1-2月",
        appearTime: "全天",
    },
    {
        id: "50",
        name: "蜣螂",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 3000,  //卖店价格
        location: "树干",
        appearNorth: [1, 2, 12],
        appearSouth: [6, 7, 8],
        northDesc: "12-2月",
        southDesc: "6-8月",
        appearTime: "全天",
    },
    {
        id: "51",
        name: "雪隐金龟",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 300,  //卖店价格
        location: "树干",
        appearNorth: [7, 8, 9],
        appearSouth: [1, 2, 3],
        northDesc: "7-9月",
        southDesc: "1-3月",
        appearTime: "全天",
    },
    {
        id: "52",
        name: "宝石金龟",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 10000,  //卖店价格
        location: "树干",
        appearNorth: [7, 8],
        appearSouth: [1, 2],
        northDesc: "7-8月",
        southDesc: "1-2月",
        appearTime: "23-8时",
    },
    {
        id: "53",
        name: "白铜锣花金龟",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 200,  //卖店价格
        location: "树干",
        appearNorth: [7, 8, 9],
        appearSouth: [1, 2, 3],
        northDesc: "7-9月",
        southDesc: "1-3月",
        appearTime: "全天",
    },
    {
        id: "54",
        name: "歌利亚大角花金龟",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 8000,  //卖店价格
        location: "树干",
        appearNorth: [6, 7, 8, 9,],
        appearSouth: [1, 2, 3, 12],
        northDesc: "6-9月",
        southDesc: "12-3月",
        appearTime: "17-8时",
    },
    {
        id: "55",
        name: "锯锹金龟",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 2000,  //卖店价格
        location: "树干",
        appearNorth: [7, 8],
        appearSouth: [1, 2],
        northDesc: "7-8月",
        southDesc: "1-2月",
        appearTime: "全天",
    },
    {
        id: "56",
        name: "深山锹金龟",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 1000,  //卖店价格
        location: "树干",
        appearNorth: [7, 8],
        appearSouth: [1, 2],
        northDesc: "7-8月",
        southDesc: "1-2月",
        appearTime: "全天",
    },
    {
        id: "57",
        name: "大锹形虫",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 10000,  //卖店价格
        location: "树干",
        appearNorth: [7, 8],
        appearSouth: [1, 2],
        northDesc: "7-8月",
        southDesc: "1-2月",
        appearTime: "23-8时",
    },
    {
        id: "58",
        name: "彩虹锹形虫",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 6000,  //卖店价格
        location: "树干",
        appearNorth: [7, 8],
        appearSouth: [1, 2],
        northDesc: "7-8月",
        southDesc: "1-2月",
        appearTime: "19-8时",
    },
    {
        id: "59",
        name: "细身赤锹形虫",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 8000,  //卖店价格
        location: "树干",
        appearNorth: [7, 8],
        appearSouth: [1, 2],
        northDesc: "7-8月",
        southDesc: "1-2月",
        appearTime: "17-8时",
    },
    {
        id: "60",
        name: "黄金鬼锹形虫",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 12000,  //卖店价格
        location: "树干",
        appearNorth: [7, 8],
        appearSouth: [1, 2],
        northDesc: "7-8月",
        southDesc: "1-2月",
        appearTime: "17-8时",
    },
    {
        id: "61",
        name: "长颈鹿锯锹形虫",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 12000,  //卖店价格
        location: "树干",
        appearNorth: [7, 8],
        appearSouth: [1, 2],
        northDesc: "7-8月",
        southDesc: "1-2月",
        appearTime: "17-8时",
    },
    {
        id: "62",
        name: "独角仙",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 1350,  //卖店价格
        location: "树干",
        appearNorth: [7, 8],
        appearSouth: [1, 2],
        northDesc: "7-8月",
        southDesc: "1-2月",
        appearTime: "17-8时",
    },
    {
        id: "63",
        name: "高卡萨斯南阳大兜虫",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 8000,  //卖店价格
        location: "树干",
        appearNorth: [7, 8],
        appearSouth: [1, 2],
        northDesc: "7-8月",
        southDesc: "1-2月",
        appearTime: "17-8时",
    },
    {
        id: "64",
        name: "象兜虫",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 8000,  //卖店价格
        location: "树干",
        appearNorth: [7, 8],
        appearSouth: [1, 2],
        northDesc: "7-8月",
        southDesc: "1-2月",
        appearTime: "17-8时",
    },
    {
        id: "65",
        name: "长戟大兜虫",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 12000,  //卖店价格
        location: "树干",
        appearNorth: [7, 8],
        appearSouth: [1, 2],
        northDesc: "7-8月",
        southDesc: "1-2月",
        appearTime: "17-8时",
    },
    {
        id: "66",
        name: "竹节虫",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 600,  //卖店价格
        location: "树干",
        appearNorth: [7, 8, 9, 10, 11],
        appearSouth: [1, 2, 3, 4, 5],
        northDesc: "7-11月",
        southDesc: "1-5月",
        appearTime: "4-8时，17-24时",
    },
    {
        id: "67",
        name: "叶竹节虫",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 600,  //卖店价格
        ocation: "树上，假装自己是叶子",
        appearNorth: [7, 8, 9],
        appearSouth: [1, 2, 3],
        northDesc: "7-9月",
        southDesc: "1-3月",
        appearTime: "全天",
    },
    {
        id: "68",
        name: "蓑衣虫",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 600,  //卖店价格
        location: "摇晃树掉落",
        appearNorth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        appearSouth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        northDesc: "全年",
        southDesc: "全年",
        appearTime: "全天",
    },
    {
        id: "69",
        name: "蚂蚁",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 80,  //卖店价格
        location: "腐烂的大头菜",
        appearNorth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        appearSouth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        northDesc: "全年",
        southDesc: "全年",
        appearTime: "全天",
    },
    {
        id: "70",
        name: "寄居蟹",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 1000,  //卖店价格
        location: "海滩",
        appearNorth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        appearSouth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        northDesc: "全年",
        southDesc: "全年",
        appearTime: "19-8时",
    },
    {
        id: "71",
        name: "海蟑螂",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 200,  //卖店价格
        location: "海滩岩地",
        appearNorth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        appearSouth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        northDesc: "全年",
        southDesc: "全年",
        appearTime: "全天",
    },
    {
        id: "72",
        name: "苍蝇",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 60,  //卖店价格
        location: "空罐头、旧靴子、旧轮胎附近",
        appearNorth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        appearSouth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        northDesc: "全年",
        southDesc: "全年",
        appearTime: "全天",
    },
    {
        id: "73",
        name: "蚊子",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 130,  //卖店价格
        location: "声音提示",
        appearNorth: [6, 7, 8, 9],
        appearSouth: [1, 2, 3, 12],
        northDesc: "6-9月",
        southDesc: "12-3月",
        appearTime: "17-4时",
    },
    {
        id: "74",
        name: "跳蚤",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 70,  //卖店价格
        location: "居民身上",
        appearNorth: [4, 5, 6, 7, 8, 9, 10, 11],
        appearSouth: [1, 2, 3, 4, 5, 10, 11, 12],
        northDesc: "4-11月",
        southDesc: "10-5月",
        appearTime: "全天",
    },
    {
        id: "75",
        name: "蜗牛",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 250,  //卖店价格
        location: "雨天石头",
        appearNorth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        appearSouth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        northDesc: "全年",
        southDesc: "全年",
        appearTime: "全天",
    },
    {
        id: "76",
        name: "鼠妇",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 250,  //卖店价格
        location: "敲击岩石",
        appearNorth: [1, 2, 3, 4, 5, 6, 9, 10, 11, 12],
        appearSouth: [3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        northDesc: "9-6月",
        southDesc: "3-12月",
        appearTime: "23-16时",
    },
    {
        id: "77",
        name: "蜈蚣",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 300,  //卖店价格
        location: "敲击岩石",
        appearNorth: [1, 2, 3, 4, 5, 6, 9, 10, 11, 12],
        appearSouth: [3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        northDesc: "9-6月",
        southDesc: "3-12月",
        appearTime: "16-23时",
    },
    {
        id: "78",
        name: "蜘蛛",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 600,  //卖店价格
        location: "摇晃树干",
        appearNorth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        appearSouth: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
        northDesc: "全年",
        southDesc: "全年",
        appearTime: "18-8时",
    },
    {
        id: "79",
        name: "狼蛛",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 8000,  //卖店价格
        location: "草地、地面",
        appearNorth: [1, 2, 3, 4, 11, 12],
        appearSouth: [5, 6, 7, 8, 9, 10],
        northDesc: "11-4月",
        southDesc: "5-10月",
        appearTime: "19-4时",
    },
    {
        id: "80",
        name: "蝎子",
        icon: "",
        shadow: "",
        shadowIcon: "",
        sellPrice: 8000,  //卖店价格
        location: "草地、地面",
        appearNorth: [5, 6, 7, 8, 9, 10],
        appearSouth: [1, 2, 3, 4, 11, 12],
        northDesc: "5-10月",
        southDesc: "11-4月",
        appearTime: "19-4时",
    }
]